name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Test
      run: |
        go get ./...
        go test -v
    
    - name: Build
      run: |
        go get ./...
        go build -trimpath -buildmode=plugin -o dnf.so -v ./...

    - name: Upload an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vib plugin
        path: ./dnf.so
